# Generated by Django 2.1.7 on 2019-03-13 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategoria')),
                ('description', models.TextField(max_length=500, verbose_name='Opis')),
            ],
            options={
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa działu')),
            ],
            options={
                'verbose_name_plural': 'Działy',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Tytuł dokumentu')),
                ('document_number', models.CharField(max_length=50, verbose_name='Numer dokumentu/procedury')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nazwa produktu')),
                ('customer_number', models.IntegerField(verbose_name='Numer produktu')),
            ],
            options={
                'verbose_name_plural': 'Produkty',
            },
        ),
    ]
