# Generated by Django 2.1.7 on 2019-03-29 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name_plural': 'Dokumenty'},
        ),
        migrations.AddField(
            model_name='document',
            name='department',
            field=models.ManyToManyField(blank=True, to='dms.Department', verbose_name='Działy'),
        ),
        migrations.AddField(
            model_name='document',
            name='product',
            field=models.ManyToManyField(blank=True, to='dms.Product', verbose_name='Produkty'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.Category', verbose_name='Kategoria'),
        ),
    ]
