# Generated by Django 2.1.7 on 2019-04-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_auto_20190329_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Dział', 'verbose_name_plural': 'Działy'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Dokument', 'verbose_name_plural': 'Dokumenty'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
        migrations.AddField(
            model_name='document',
            name='document_file',
            field=models.FileField(default=-1.0, upload_to='', verbose_name='Plik dokumentu'),
            preserve_default=False,
        ),
    ]
