# Generated by Django 2.1.7 on 2019-04-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0003_auto_20190402_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tytuł formularza')),
                ('test', models.FilePathField()),
            ],
            options={
                'verbose_name': 'Formularz',
                'verbose_name_plural': 'Formularze',
            },
        ),
    ]
